# Generated by Django 6.0 on 2026-02-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdetail',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstdetail',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
