# Generated by Django 6.0 on 2026-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
