# Generated by Django 6.0 on 2026-02-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_product_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
