# Generated by Django 6.0 on 2026-02-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_product_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessdetail', to_field='code'),
        ),
    ]
