# Generated by Django 6.0 on 2026-02-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_order_name_phone_fields'),
        ('users', '0003_savedaddress_name_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer', to_field='username'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='business_order',
        ),
    ]
