# Generated by Django 6.0 on 2026-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_staffuser_staffprivileges_alter_staff_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='avs_wallet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
