from django.urls import path
from . import views
from .config_views import config_view, add_category, edit_category, add_unit, edit_unit, add_gst, edit_gst
from users.views import staff_profile_edit

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('update-address/', views.update_address, name='update_address'),
    path('set-default-address/', views.set_default_address, name='set_default_address'),
    path('confirm-order/', views.confirm_order, name='confirm_order'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('login/', views.customer_login_view, name='login'),
    path('staff-login/', views.login_view, name='staff_login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('seller/', views.seller_dashboard, name='seller_dashboard'),
    path('seller/profile/', staff_profile_edit, name='staff_profile_edit'),
    path('seller/config/', config_view, name='config'),
    path('seller/config/add-category/', add_category, name='add_category'),
    path('seller/config/edit-category/<int:id>/', edit_category, name='edit_category'),
    path('seller/config/add-unit/', add_unit, name='add_unit'),
    path('seller/config/edit-unit/<int:id>/', edit_unit, name='edit_unit'),
    path('seller/config/add-gst/', add_gst, name='add_gst'),
    path('seller/config/edit-gst/<int:id>/', edit_gst, name='edit_gst'),
    path('seller/add-product/', views.add_product, name='add_product'),
    path('seller/edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('seller/orders/', views.manage_orders, name='manage_orders'),
    path('seller/staff/', views.manage_staff, name='manage_staff'),
    path('seller/add-staff/', views.add_staff, name='add_staff'),
    path('management/', views.management_dashboard, name='management_dashboard'),
    path('orders/', views.order_history, name='order_history'),
    path('payment-history/', views.payment_history, name='payment_history'),
    path('wallet/', views.wallet_view, name='wallet'),
    path('view-invoice/<str:order_id>/', views.download_invoice, name='download_invoice'),
    path('delete-address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('edit-address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('<str:username>/profile/', views.profile_view, name='profile'),
]
