# Generated by Django 6.0 on 2026-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_user',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('staff_role', models.CharField(choices=[('Seller-Admin', 'Seller-Admin'), ('Shop-Admin', 'Shop-Admin'), ('Seller-Staff', 'Seller-Staff'), ('Shop-Staff', 'Shop-Staff'), ('Management-Admin', 'Management-Admin'), ('Management-Staff', 'Management-Staff')], max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('business_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.businessdetail', to_field='code')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.staffuser', to_field='username')),
            ],
            options={
                'db_table': 'business_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_orders', models.BooleanField(default=False)),
                ('manage_products', models.BooleanField(default=False)),
                ('manage_reports', models.BooleanField(default=False)),
                ('manage_payments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='seller.staff')),
            ],
            options={
                'db_table': 'staff_privileges',
            },
        ),
        migrations.CreateModel(
            name='StaffUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='seller.staffuser', to_field='username')),
            ],
            options={
                'db_table': 'staff_user_profile',
            },
        ),
    ]
