# Generated by Django 6.0 on 2026-03-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_role',
            new_name='role',
        ),
    ]
