# Generated by Django 6.0 on 2026-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuserprofile',
            name='aadhaar_attachment',
            field=models.FileField(blank=True, null=True, upload_to='staff_kyc/'),
        ),
        migrations.AddField(
            model_name='staffuserprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='staffuserprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffuserprofile',
            name='pan_attachment',
            field=models.FileField(blank=True, null=True, upload_to='staff_kyc/'),
        ),
        migrations.AddField(
            model_name='staffuserprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
