# Generated by Django 6.0 on 2026-03-22 16:37

import seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_add_kyc_fields_to_staffuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=seller.models._staff_pic_path),
        ),
    ]
