# Generated by Django 6.0 on 2026-03-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_staffuser_staffprivileges_alter_staff_username_and_more'),
        ('users', '0003_savedaddress_name_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuserprofile',
            name='username',
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
        migrations.DeleteModel(
            name='StaffUserProfile',
        ),
    ]
