# Generated by Django 6.0 on 2026-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_order_bill_address1_alter_order_bill_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='items_details',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
