# Generated by Django 6.0 on 2026-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_order_cancelled_comments_order_confirmed_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='business_type',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Shop', 'Shop'), ('Retailer', 'Retailer'), ('Service', 'Service'), ('Management', 'Management')], max_length=100),
        ),
    ]
