# Generated by Django 6.0 on 2026-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_deliverycharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryzone',
            name='distance_range_km',
            field=models.CharField(help_text='e.g. 0-10 km', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
