# Generated by Django 6.0 on 2026-03-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_deliveryzone_distance_range_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryzone',
            name='estimated_days_max',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='estimated_days_min',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='pincode_from',
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='distance_range_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_address', models.CharField(blank=True, max_length=500, null=True)),
                ('min_amount_free_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('business_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.businessdetail', to_field='code')),
            ],
            options={
                'db_table': 'business_deliverysettings',
            },
        ),
    ]
