# Generated by Django 6.0 on 2026-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_deliveryzone_estimated_days_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverysettings',
            name='store_address',
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='store_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='store_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='store_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
