# Generated by Django 6.0 on 2026-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_deliverysettings_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='store_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
