# Generated by Django 6.0 on 2026-03-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_deliverysettings_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ship_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
