# Generated by Django 6.0 on 2026-03-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_product_ship_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='delivery_free',
            field=models.BooleanField(default=True),
        ),
    ]
