# Generated by Django 6.0 on 2026-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_deliverysettings_delivery_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='sheep_free',
            field=models.BooleanField(default=True),
        ),
    ]
