# Generated by Django 6.0 on 2026-03-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_deliverysettings_sheep_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverysettings',
            old_name='sheep_free',
            new_name='ship_free',
        ),
    ]
