# Generated by Django 6.0 on 2026-03-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_order_delivery_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryWeightSlab',
        ),
    ]
