# Generated by Django 6.0 on 2026-03-22 16:37

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_remove_deliveryweightslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=management.models._product_image_path),
        ),
    ]
