# Generated by Django 6.0 on 2026-03-22 16:37

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models._customer_pic_path),
        ),
    ]
